dist: focal
language: node_js
node_js: 'lts/*'

services:
  - docker

branches:
  only:
    - develop
    - master
    - /^((hotfix|feature|release|dependabot)\/.*)$/

stages:
  - test
  - deploy

jobs:
  include:
    - script:
        - bash ./scripts/unitTest.sh
        - npm run coverage-codecov
      name: test:mocha
    - script: bash ./scripts/e2eTest.sh
      name: "test:end-to-end"
      after_failure:
        - cat /home/travis/.npm/_logs/*debug.log
    - stage: deploy
      if: NOT fork
      script:
        - ./scripts/build.sh
      name: build_and_push
      language: generic
      env:
        - GIT_SHA=$( git rev-parse HEAD )
        - DOCKERTAG=$( echo $TRAVIS_BRANCH | tr -s "[:punct:]" "-" )
      after_failure:
        - cat /home/travis/.npm/_logs/*debug.log
